name: build

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Checkout Principia src
        uses: actions/checkout@v4
        with:
          repository: Bithack/principia
          path: src

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y luajit

      - name: Build
        run: |
          luajit build.lua

      - name: Upload output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: bin/
